[package]
name = "myproject"
version = "0.1.0"
authors = ["dem"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "mod_enums"
path = "src/bin/mod_enums.rs"
